network:
  ethernets:
    eno1:
      dhcp4: true
    eno2:
      dhcp4: false
      addresses:
      - 192.168.2.10/24
    eno3:
      dhcp4: true
    eno4:
      dhcp4: false
      addresses:
      - 10.10.0.3/22
      gateway4: 10.10.0.1
      nameservers:
       addresses:
       - 8.8.8.8
  version: 2